apiVersion: xl/v2
kind: Blueprint

metadata:
  name: Docker Sample
  description: |
    The blueprint deploys a simple application in Docker container into your local Docker setup.
    XL Deploy does the deployment, while XL Release orchestrates everything.
  author: XebiaLabs
  version: 2.0
  instructions: Please read the generated file "xebialabs/USAGE.md" for further usage instructions.

spec:
  files:
  - path: xebialabs.yaml
  - path: xebialabs/USAGE.md

  includeBefore:
  - blueprint: docker/environment
    parameterOverrides:
    - name: Standalone
      value: false
  - blueprint: docker/application

  includeAfter:
  - blueprint: xl-devops-platform
    parameterOverrides:
    - name: UseXLDeploy
      value: true
    - name: XLDeployPort
      value: 4516
    - name: UseXLRelease
      value: false
    - name: JetPackOrEnterprise
      value: "XL Enterprise"
    - name: XLVersion
      value: "9.0"
    - name: UseDockerProxy
      value: true
    - name: UseJenkins
      value: false
