apiVersion: xl/v2
kind: Blueprint

metadata:
  name: Docker Demo Application
  description: |
    The blueprint deploys a simple application in 2 Docker containers into your local Docker setup.
    XL Deploy does the deployment, while XL Release orchestrates everything.
  author: XebiaLabs
  version: 2.0
  instructions: Please read the generated file "xebialabs/USAGE.md" for further usage instructions.

spec:
  parameters:
  - name: AppName
    type: Input
    prompt: What is the Application name?
  - name: ContainerPort
    type: Input
    prompt: At what port should the application be exposed in the container?
    default: 80
  - name: HostPort
    type: Input
    prompt: At what port should the container port be mapped in the host?
    default: 8181
  - name: BackendDockerImage
    type: Input
    prompt: What is the Docker Image (repo and path) for the Backend service?
    default: xebialabsunsupported/rest-o-rant-api
  - name: FrontendDockerImage
    type: Input
    prompt: What is the Docker Image (repo and path) for the Frontend service?
    default: xebialabsunsupported/rest-o-rant-web

  - name: GenerateDockerComposeSetup
    type: Confirm
    prompt: "Do you want to generate a docker-compose setup with the required tools to run this blueprint?"
    default: false

  includeAfter:
  - blueprint: xl-devops-platform
    includeIf: GenerateDockerComposeSetup
    parameterOverrides:
    - name: UseXLDeploy
      value: true
    - name: XLDeployPort
      value: 4516
    - name: UseXLRelease
      value: true
    - name: XLReleasePort
      value: 5516
    - name: XLVersion
      value: "9.0"
    - name: UseDockerProxy
      value: true
    - name: UseJenkins
      value: false

  files:
  - path: xebialabs/xld-environment.yaml.tmpl
  - path: xebialabs/xld-docker-apps.yaml.tmpl
  - path: xebialabs/xlr-pipeline.yaml.tmpl
  - path: xebialabs/USAGE.md.tmpl
  - path: xebialabs.yaml
