apiVersion: xl/v2
kind: Blueprint

metadata:
  name: Create infrastructure and environment for Docker
  description: |
    This blueprint defines an environment to which Docker containers can be deployed
  author: XebiaLabs
  version: 2.0
  instructions: Read xebialabs/USAGE-docker-environment.md to learn how to use this blueprint.

spec:
  parameters:
  - name: DockerURL
    type: Input
    prompt: What is the URL of the Docker engine?
    default: http://dockerproxy:2375

  files:
  - path: xebialabs/docker-environment.yaml.tmpl
  - path: xebialabs/USAGE-docker-environment.md
